### ISSUE TITLE
Internet issue problem in DDoS Program.

### ISSUE THREAD

**Issue by cuj** [DrWeabo/MaddStress#3]
Hi, I was searching for a DDoS Program, and I found this program, but unfortunately, when I start the program, I get this error, even when I'm connected to the internet.

![](https://user-images.githubusercontent.com/66434686/115605693-7fcba980-a2eb-11eb-9142-0c9f7ceefeb6.PNG)

I hope you can tell me a solution to this or fix it. thanks.

**Comment by snipeparpar** [comment]
i have the same problem

**Comment by DrWeabo** [comment]
i will fix it soon, i'm very busy w real life.. sorry for long respon..
