### ISSUE TITLE
Can't get CPU Temp

### ISSUE THREAD

**Issue by dirk2947** [DrWeabo/MaddStress#4]
Hey there, on startup it tells me that it doesn't have the priviliges to check for CPU Temp.
I started with Admin rights though, so that can't be it. 
If I would guess it is because of my AMD CPU, I can't confirm this though.
Program stays open and updates load % etc. but not usable since the error message makes everything else unclickable.
If I close the error the whole program closes.

**Comment by DrWeabo** [comment]
Hello, Good Morning @dirk2947 
Contact me on discord, i will help you..

Join here - https://discord.io/DrWeaboNEW
